language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn install
  - yarn coverage
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls
